incremental update

diff --git a/import-update b/import-update
--- a/import-update
+++ b/import-update
@@ -7,15 +7,27 @@ okapi_token=$(cat okapi.token)
 infile="ids"
 profileName="ZKB Items, update on UUID"
 
+if [[ "${profileName,,}" =~ "uuid" ]]; then infile="uuids";fi
+if [[ "${profileName,,}" =~ "barcode" ]]; then infile="barcodes";fi
+
+if [[ ! -f "${infile}" ]];then echo "You must supply a file named \"${infile}\""; exit;fi
+
+echo "Matching on file named \"${infile}\""
+
 batch=0
 total=0
 numrecs=$(wc -l ${infile} |cut -f1 -d " ")
+echo "${numrecs} records detected"
+
 total_arr=() # needed to remember variable from loop
 
 dos2unix "${infile}"
 idfile=$(head -1 "${infile}" |wc -c)
 
-if [[ ${#idfile} -lt 38 ]];then idfile="yes";fi
+if [[ ${#idfile} -lt 38 ]];then 
+	idfile="yes"
+	echo "File of ${infile} detected. Building MARC_JSON objects"
+fi
 
 user_id=$(cat okapi.token |base64 -di 2>/dev/null |jq -r 'select(.user_id != null) |.user_id' 2>/dev/null)
 
@@ -46,17 +58,21 @@ post_records() {
 		cat ${currentfile} | jq -nR   --arg BATCHUUID ${batchuuid} --argjson BATCHSIZE ${batchsize} --argjson TOTAL ${total} '
 				{"initialRecords": [inputs as $ID 
 				| select(($ID|length)>0) 
-				|{"leader":"00047cam a22000370  4500","fields":[{"001":$ID}]} ]} 
+				| {"record":{"leader":"00047cam a22000370  4500","fields":[{"001":$ID}]}}]}
 				| .id = $BATCHUUID |.recordsMetadata.last = false | .recordsMetadata.counter = $BATCHSIZE 
 				| .recordsMetadata.total = $TOTAL | .recordsMetadata.contentType = "MARC_JSON" ' > tmp_processfile
 	fi
+
+	curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d @tmp_processfile "${okapi_url}/change-manager/jobExecutions/${parentJobExecutionId}/records"
 }
 
 #####################################
 
 all_job_profiles=$(curl --http1.1 -s -w '\n' -X GET -H "Accept: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" "${okapi_url}/data-import-profiles/jobProfiles?limit=1000")
 
-jobProfileId=$(echo "${all_job_profiles}" |jq -r ".jobProfiles[] | select(.name==\"${profileName}\") | .id")
+jobProfileInfo=$(echo "${all_job_profiles}" |jq -rc ".jobProfiles[] | select(.name==\"${profileName}\") 
+	|del(.userInfo) |del(.parentProfiles) |del(.childProfiles) | del(.hidden) |del(.metadata) |del(.deleted) |del(.description)")
+jobProfileId=$(echo "${jobProfileInfo}" |jq -r .id)
 
 
 if ! [[ $jobProfileId =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
@@ -69,10 +85,9 @@ fi
 apicall=$(curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "{\"sourceType\": \"ONLINE\", \"userId\": \"${user_id}\"}" "${okapi_url}/change-manager/jobExecutions")
 
 parentJobExecutionId=$(jq -r .parentJobExecutionId <<< "${apicall}")
-jobExecutionId=$(jq -r '.jobExecutions |= sort_by(.hrid) | '.jobExecutions[-1].id <<< "${apicall}")
 
-if ! [[ $parentJobExecutionId =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ && jobExecutionId =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]];then
-	echo "Failed to obtain parentJobExecutionId or jobExecutionId. Exiting."
+if ! [[ $parentJobExecutionId =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]];then
+	echo "Failed to obtain parentJobExecutionId Exiting."
 	echo
 	echo "${apicall}"
 	exit
@@ -81,17 +96,16 @@ fi
 echo "posting {\"id\": \"${jobProfileId}\", \"name\": \"${profileName}\", \"dataType\": \"MARC\"}"
 
 
-apicall=$(curl --http1.1 -s -w '\n' -X PUT -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "{\"id\": \"${jobProfileId}\", \"name\": \"${profileName}\", \"dataType\": \"MARC\"}" "${okapi_url}/change-manager/jobExecutions/${parentJobExecutionId}/jobProfile")
+apicall=$(curl --http1.1 -s -w '\n' -X PUT -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "${jobProfileInfo}" "${okapi_url}/change-manager/jobExecutions/${parentJobExecutionId}/jobProfile")
 
-jq -r . <<< "${apicall}"
+sleep 5
 
 for recordfile in $(ls);do
 	post_records ${recordfile} 
 	total_arr+=($total) # array needed to remember variable outside loop
 done
 
+#curl --http1.1 -s -w '\n' -X POST -H "Content-type: application/json" -H "X-Okapi-Tenant: ${tenant}" -H "x-okapi-token: ${okapi_token}" -d "{ \"id\": \"$(uuidgen)\", \"recordsMetadata\": { \"last\": true, \"counter\": \"${numrecs}\", \"total\": \"${numrecs}\", \"contentType\":\"MARC_JSON\" }, \"initialRecords\": []}" "${okapi_url}/change-manager/jobExecutions/${parentJobExecutionId}/jobProfile"
+
 exit
-
-
-
-
+rm tmp_processfile
