add negative switch

diff --git a/marcdelete b/marcdelete
--- a/marcdelete
+++ b/marcdelete
@@ -1,3 +1,22 @@
+#!/usr/bin/bash
+
+posneg_regex='^[1-9]'
+
+while getopts "n" opt; do
+  case $opt in
+    n)
+      posneg_regex='^0'
+      ;;
+    \?)
+      echo "Error: Invalid option -$OPTARG" >&2
+      echo "Usage: $0 [-n]" >&2
+      exit 1
+      ;;
+  esac
+done
+
+shift $((OPTIND - 1))
+
 if [[ -z $1 ]];then
 	echo "Deletes specified tags matching a regex"
 	echo "Tags can be expressed as a regex"
@@ -118,7 +137,7 @@ function rebuild_directory(){
 		
 		field_content = substr(record_content, starting_pos, field_length)
 
-		if (marc_tag in deletelist && match(field_content, SEARCH)) {
+		if (marc_tag in deletelist && (match(field_content, SEARCH) ~ POSNEG_REGEX)) {
 			fix_directory = 1
 			deleted_fields_total++
 			deleted_fields_record++
@@ -160,7 +179,7 @@ ENDOFAWK
 echo -e "${awkscript}" > tmp_marcdelete
 chmod 700 tmp_marcdelete
 
-awk -v RS=$'\x1d' -v ORS=$'\x1d' -v FS=$'\x1e' -v OFS=$'\x1e' -v SFS=$'\x1f' -v DELETETAGS="${deletetags[*]}" -v SUBFIELD="${subfield}" -v SEARCH="${search}" -v OUTFILE="${outfile}" -b -f tmp_marcdelete "${infile}"
+awk -v RS=$'\x1d' -v ORS=$'\x1d' -v FS=$'\x1e' -v OFS=$'\x1e' -v SFS=$'\x1f' -v DELETETAGS="${deletetags[*]}" -v SUBFIELD="${subfield}" -v SEARCH="${search}" -v POSNEG_REGEX=${posneg_regex} -v OUTFILE="${outfile}" -b -f tmp_marcdelete "${infile}"
 
 sleep 1
 rm -f tmp_marcreplace
